# Generated by Django 6.0.1 on 2026-01-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del servidor (ej: Localhost)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, help_text='SO y Versión', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(help_text='Uso de CPU en %')),
                ('ram_usage', models.FloatField(help_text='Uso de RAM en %')),
                ('disk_usage', models.FloatField(help_text='Uso de Disco principal en %')),
                ('gpu_usage', models.FloatField(blank=True, help_text='Uso de GPU en %', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitor.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
