# Generated by Django 6.0.1 on 2026-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmetric',
            name='gpu_usage',
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='disk_free',
            field=models.FloatField(blank=True, help_text='Espacio libre en disco principal (GB)', null=True),
        ),
    ]
