# Generated by Django 6.0.1 on 2026-02-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_systemmetric_gpu_usage_systemmetric_disk_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemmetric',
            name='disk_free',
        ),
        migrations.AddField(
            model_name='systemmetric',
            name='swap_usage',
            field=models.FloatField(blank=True, help_text='Uso de Memoria Virtual (Swap) en %', null=True),
        ),
    ]
